#%RAML 1.0 NamedExample

- text: "RT @NASA360: The 2021 Atlantic hurricane season began in June and @NOAA is predicting an above average number of named storms. At NASA, we’…"
  url: https://api.twitter.com/1.1/search/tweets.json?q=nasa&result_type=popular
  author: NASA360

- text: Rusia probó una forma de aerosol nasal de su vacuna contra el coronavirus Sputnik V que es adecuada para niños de 8… https://t.co/x5VZ542b6q
  url: https://t.co/x5VZ542b6q
  author: pagina12