http:
  port: "8081"
  
twitter:
  protocol: "https"
  host: "api.twitter.com"
  resourcepath: "/1.1/search"
  
query:
  parameters:
    default:
      hours: "5"
      result_type: "popular"
      
token: "AAAAAAAAAAAAAAAAAAAAAI4OHgEAAAAAlbk0HSIAqcc3havrrU9j2NeAQ34%3DzJmzwHuQerd8JJ2TeuHfqwKgBt6bK4tk93w3ocBB2vPuKMF3cG"